### ISSUE TITLE
"Find & Replace layer names" opens blank window

### ISSUE THREAD

**Issue by najiglass** [rodi01/RenameIt#68] opened 2018-01-31 18:44 UTC
When I select artboards and choose the Find & Replace option, it takes a while to open, and I then see a blank window.
Version 3.7.0. Tried reinstalling as well, no lock.
Works well on my other Macbook, but not on this one. They both have High Sierra and the same Sketch version.

<img width="524" alt="screen shot 2018-01-31 at 10 41 20 am" src="https://user-images.githubusercontent.com/12573714/35640845-4cde9338-0673-11e8-8859-eae0b8d8a24d.png">

**Comment by rodi01** [comment] 2018-01-31 18:52
@najiglass Sorry about that 😞
Could you take a look on the console for anything error? I've never seen this before. 
/Applications/Utilities/Console.app

it should be under report

![screen shot 2018-01-31 at 10 50 14 am](https://user-images.githubusercontent.com/52461/35641318-b606ea76-0674-11e8-9c6b-fc06cbf6034d.png)

**Comment by chenkes** [comment] 2018-02-02 02:12
Same error for me...

Reporting: "No WebView present. Event cannot be posted to the web UI.
 «Plugin Output»" in Console, Output...

Currently using Sketch 48.2

**Comment by rodi01** [comment] 2018-02-02 03:23
@chenkes I will take a look.

**Comment by najiglass** [comment] 2018-02-03 00:25
I get all of this if I filter on "Sketch", at the moment I open the Find & Replace.

default	16:23:11.984200 -0800	Sketch	Task <2F1A61DF-DAF1-4F94-8C60-D092D0ED4ADA>.<941> now using Connection 271
default	16:23:11.984327 -0800	Sketch	Task <2F1A61DF-DAF1-4F94-8C60-D092D0ED4ADA>.<941> sent request, body N
default	16:23:11.984934 -0800	Sketch	Task <2F1A61DF-DAF1-4F94-8C60-D092D0ED4ADA>.<941> received response, status 200 content K
default	16:23:11.985088 -0800	Sketch	Task <2F1A61DF-DAF1-4F94-8C60-D092D0ED4ADA>.<941> response ended
default	16:23:22.904390 -0800	Sketch	0x194858000 - DocumentLoader::startLoadingMainResource: Returning empty document (frame = 0x155d95c30, main = 1)
default	16:23:22.904466 -0800	Sketch	Memory usage info dump at MainFrameLoadCompleted:
default	16:23:22.904488 -0800	Sketch	  phys_footprint: 2044530688
default	16:23:22.904524 -0800	Sketch	  virtual_size: 9982926848
default	16:23:22.904540 -0800	Sketch	  resident_size: 2341515264
default	16:23:22.904555 -0800	Sketch	  internal: 2263904256
default	16:23:22.904571 -0800	Sketch	  compressed: 162164736
default	16:23:22.904586 -0800	Sketch	  pagecache_page_count: 0
default	16:23:22.904600 -0800	Sketch	  javascript_gc_heap_capacity: 52286904
default	16:23:22.904615 -0800	Sketch	  document_count: 25
default	16:23:22.904630 -0800	Sketch	  javascript_gc_heap_extra_memory_size: 11539592
default	16:23:22.906639 -0800	Sketch	Memory usage info dump at MainFrameLoadStarted:
default	16:23:22.906697 -0800	Sketch	  phys_footprint: 2044571648
default	16:23:22.906717 -0800	Sketch	  virtual_size: 9982926848
default	16:23:22.906733 -0800	Sketch	  resident_size: 2341556224
default	16:23:22.906748 -0800	Sketch	  internal: 2263945216
default	16:23:22.906762 -0800	Sketch	  compressed: 162164736
default	16:23:22.906787 -0800	Sketch	  pagecache_page_count: 0
default	16:23:22.906810 -0800	Sketch	  javascript_gc_heap_capacity: 52286904
default	16:23:22.906833 -0800	Sketch	  document_count: 25
default	16:23:22.906941 -0800	Sketch	  javascript_gc_heap_extra_memory_size: 11539592
default	16:23:22.907197 -0800	Sketch	0x7fba9d5f4ef0 - FrameLoader::prepareForLoadStart: Starting frame load (frame = 0x155d95c30, main = 1)
default	16:23:22.907262 -0800	Sketch	0x194851000 - DocumentLoader::startLoadingMainResource: Starting load (frame = 0x155d95c30, main = 1)
default	16:23:23.425779 -0800	Sketch	*** WebKit discarded an uncaught exception in the webView:didChangeLocationWithinPageForFrame: delegate: <MOJavaScriptException> TypeError: undefined is not an object (evaluating '(C=r(C)).pluginAction')
default	16:23:23.437815 -0800	Sketch	Memory usage info dump at MainFrameLoadCompleted:
default	16:23:23.437863 -0800	Sketch	  phys_footprint: 2227888128
default	16:23:23.437887 -0800	Sketch	  virtual_size: 9970855936
default	16:23:23.437905 -0800	Sketch	  resident_size: 2405498880
default	16:23:23.437923 -0800	Sketch	  internal: 2334191616
default	16:23:23.437939 -0800	Sketch	  compressed: 162164736
default	16:23:23.437956 -0800	Sketch	  pagecache_page_count: 0
default	16:23:23.437972 -0800	Sketch	  javascript_gc_heap_capacity: 54646056
default	16:23:23.438031 -0800	Sketch	  document_count: 25
default	16:23:23.438063 -0800	Sketch	  javascript_gc_heap_extra_memory_size: 11539592
default	16:23:23.438176 -0800	Sketch	0x7fba9d5f4ef0 - FrameLoader::checkLoadCompleteForThisFrame: Finished frame load (frame = 0x155d95c30, main = 1)
default	16:23:23.444039 -0800	Sketch	TIC TCP Conn Start [283:0x604000b66480]
default	16:23:23.444164 -0800	Sketch	Task <988188F1-CE84-4F99-964D-B635C9BB63FF>.<0> setting up Connection 283
default	16:23:23.444280 -0800	Sketch	TIC TCP Conn Start [284:0x60400077cc80]
default	16:23:23.444481 -0800	Sketch	Task <E95C63E4-D7C2-46CE-9359-0C9411EB724D>.<0> setting up Connection 284
default	16:23:23.444709 -0800	Sketch	TIC TCP Conn Start [285:0x608000b720c0]
default	16:23:23.444833 -0800	Sketch	Task <468351AC-36AA-4E8B-94BE-D0F4D6A567AF>.<0> setting up Connection 285
default	16:23:23.490467 -0800	Sketch	TIC TCP Conn Connected [283:0x604000b66480]: Err(16)
default	16:23:23.490732 -0800	Sketch	TIC TCP Conn Event [283:0x604000b66480]: 1
default	16:23:23.491248 -0800	Sketch	Task <988188F1-CE84-4F99-964D-B635C9BB63FF>.<0> now using Connection 283
default	16:23:23.491442 -0800	Sketch	Task <988188F1-CE84-4F99-964D-B635C9BB63FF>.<0> sent request, body N
default	16:23:23.494192 -0800	Sketch	TIC TCP Conn Connected [284:0x60400077cc80]: Err(16)
default	16:23:23.494318 -0800	Sketch	TIC TCP Conn Event [284:0x60400077cc80]: 1
default	16:23:23.494618 -0800	Sketch	Task <E95C63E4-D7C2-46CE-9359-0C9411EB724D>.<0> now using Connection 284
default	16:23:23.494734 -0800	Sketch	Task <E95C63E4-D7C2-46CE-9359-0C9411EB724D>.<0> sent request, body N
default	16:23:23.500032 -0800	Sketch	TIC TCP Conn Connected [285:0x608000b720c0]: Err(16)
default	16:23:23.500151 -0800	Sketch	TIC TCP Conn Event [285:0x608000b720c0]: 1
default	16:23:23.500415 -0800	Sketch	Task <468351AC-36AA-4E8B-94BE-D0F4D6A567AF>.<0> now using Connection 285
default	16:23:23.500568 -0800	Sketch	Task <468351AC-36AA-4E8B-94BE-D0F4D6A567AF>.<0> sent request, body N
default	16:23:23.513340 -0800	Sketch	Task <E95C63E4-D7C2-46CE-9359-0C9411EB724D>.<0> received response, status 200 content K
default	16:23:23.513498 -0800	Sketch	Task <E95C63E4-D7C2-46CE-9359-0C9411EB724D>.<0> response ended
default	16:23:23.521183 -0800	Sketch	Task <468351AC-36AA-4E8B-94BE-D0F4D6A567AF>.<0> received response, status 200 content K
default	16:23:23.521327 -0800	Sketch	Task <468351AC-36AA-4E8B-94BE-D0F4D6A567AF>.<0> response ended
default	16:23:23.542391 -0800	Sketch	Task <A6C1358B-901F-4BC6-9408-F4C833AEB24D>.<942> now using Connection 271
default	16:23:23.542517 -0800	Sketch	Task <A6C1358B-901F-4BC6-9408-F4C833AEB24D>.<942> sent request, body N
default	16:23:23.543492 -0800	Sketch	Task <A6C1358B-901F-4BC6-9408-F4C833AEB24D>.<942> received response, status 200 content K
default	16:23:23.543622 -0800	Sketch	Task <A6C1358B-901F-4BC6-9408-F4C833AEB24D>.<942> response ended
default	16:23:23.588293 -0800	Sketch	Task <988188F1-CE84-4F99-964D-B635C9BB63FF>.<0> received response, status 200 content C
default	16:23:23.588504 -0800	Sketch	Task <988188F1-CE84-4F99-964D-B635C9BB63FF>.<0> response ended
default	16:23:23.597456 -0800	Sketch	Task <BBB1C0B1-869B-4A75-B967-BE432CE35570>.<0> now using Connection 283
default	16:23:23.597651 -0800	Sketch	Task <BBB1C0B1-869B-4A75-B967-BE432CE35570>.<0> sent request, body N
default	16:23:23.615415 -0800	Sketch	Task <BBB1C0B1-869B-4A75-B967-BE432CE35570>.<0> received response, status 200 content K
default	16:23:23.615613 -0800	Sketch	Task <BBB1C0B1-869B-4A75-B967-BE432CE35570>.<0> response ended
default	16:23:28.653607 -0800	Sketch	TIC TCP Conn Event [282:0x60800096d5c0]: 3
error	16:23:28.653632 -0800	Sketch	TIC TCP Conn Failed [282:0x60800096d5c0]: 3:-9802 Err(-9802)
default	16:23:28.653652 -0800	Sketch	TIC TCP Conn Cancel [282:0x60800096d5c0]
default	16:23:28.653735 -0800	Sketch	NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
error	16:23:28.653795 -0800	Sketch	Task <404CA863-7875-4FE5-BC78-E32513139518>.<0> HTTP load failed (error code: -1200 [3:-9802])
default	16:23:28.655586 -0800	Sketch	TIC TCP Conn Destroyed [282:0x60800096d5c0]
default	16:23:28.655739 -0800	Sketch	TIC Enabling TLS [286:0x604000b7ad00]
default	16:23:28.655773 -0800	Sketch	TIC TCP Conn Start [286:0x604000b7ad00]
default	16:23:28.655899 -0800	Sketch	Task <737395CD-99EA-4ADD-85FC-C582C7B63046>.<0> setting up Connection 286
default	16:23:28.815030 -0800	Sketch	TIC TLS Event [286:0x604000b7ad00]: 1, Pending(0)
default	16:23:28.913343 -0800	Sketch	TIC TLS Event [286:0x604000b7ad00]: 2, Pending(0)
default	16:23:28.914011 -0800	Sketch	TIC TLS Event [286:0x604000b7ad00]: 11, Pending(0)
default	16:23:28.914723 -0800	Sketch	TIC TLS Event [286:0x604000b7ad00]: 12, Pending(0)
default	16:23:28.914791 -0800	Sketch	TIC TLS Event [286:0x604000b7ad00]: 14, Pending(0)

**Comment by rodi01** [comment] 2018-02-03 01:24
Thanks @najiglass. I'll take a look on it this weekend.

**Comment by najiglass** [comment] 2018-02-24 01:00
@rodi01 Any updates? Any alternatives that you know of in the meantime? Thanks!

**Comment by rodi01** [comment] 2018-02-24 02:06
@najiglass Can you try the latest update?
I've changed a couple of things but I don't think it has fixed your issue. It's hard to fix it since I can't reproduce it on my end, I'm trying to get help on this from other plugin developers.
Sorry for the delay.

**Comment by najiglass** [comment] 2018-02-24 19:30
Thanks! Unfortunately no, still doesn’t work with the new update.

**Comment by rodi01** [comment] 2018-02-28 04:52
@najiglass if I send you a debug version of the plugin could you take a screenshot of the inspector and send it to me? 

Sorry for the hassle but I can’t find a way to reproduce it.

**Comment by najiglass** [comment] 2018-02-28 16:52
Yes for sure!

Andrey

**Comment by rodi01** [comment] 2018-03-04 22:07
Sorry for the delay @najiglass, it's been a busy week. 

Here is the debug version: [https://cl.ly/pwZZ](https://cl.ly/pwZZ)
Could you please download and install the plugin?

Once you've done that, run the find and replace command, you will see the empty screen. 

Right click anywhere on the screen and you should see a menu: 
<img width="178" alt="inspect" src="https://user-images.githubusercontent.com/52461/36951125-97192b02-1fb4-11e8-9a10-12d2bd34ad10.png">

Click on inspect Element and you should see this:
<img width="1253" alt="screen shot 2018-03-04 at 1 48 28 pm" src="https://user-images.githubusercontent.com/52461/36951150-ecbb4130-1fb4-11e8-9d19-b43d81058043.png">

Switch to the console tab:
<img width="1253" alt="screen shot 2018-03-04 at 1 48 48 pm" src="https://user-images.githubusercontent.com/52461/36951154-109c7e16-1fb5-11e8-8b46-d7df6fab0302.png">


Can you screenshot that and send it to me? Hopefully I can see the error there. 

Thanks again for your patience.

**Comment by najiglass** [comment] 2018-03-06 01:23
Thanks! Unfortunately Chrome won't let me download that file, it's blocked
as being dangerous.

Would you know why?

**Comment by rodi01** [comment] 2018-03-06 02:19
@najiglass this is so strange. I wonder if chrome doesn't like cloud app links. I re-uploaded it to dropbox here is the link: https://www.dropbox.com/s/rufuigtvaj7gzwn/Rename-It.sketchplugin.zip?dl=0

**Comment by giuseppebergman** [comment] 2018-03-07 18:54
Hey,
Same bug here, with Sketch 48.2 and plugin v3.7.2.
Here's the screenshot (in two pieces) made with your debug version as suggested to najiglass:
![capture d ecran 2018-03-07 a 19h52 45](https://user-images.githubusercontent.com/11982783/37111862-2748c87a-2241-11e8-8626-dd2c67de4d70.png)
<img width="1057" alt="capture d ecran 2018-03-07 a 19h53 42" src="https://user-images.githubusercontent.com/11982783/37111908-47a8f32e-2241-11e8-979e-783471678cb6.png">

Thanks,

Giu_

**Comment by rodi01** [comment] 2018-03-07 20:32
Thanks @giuseppebergman! This is really helpful. 

When you launch the find and replace, did you hav any later selected?

**Comment by giuseppebergman** [comment] 2018-03-07 20:38
Sure, I've tried first with more than a dozen layers selected, then just three (when I captured the log), for the same result.
I should add that there's an idle delay (several seconds) before the blank window displays.

**Comment by rodi01** [comment] 2018-03-10 19:39
@giuseppebergman can you try this build?
https://www.dropbox.com/s/x8f9i4xo9kgqxds/Rename-It-find-rename.sketchplugin.zip?dl=0

If it doesn't work, can you do the same and send me the screenshot of the console.

Thanks! Apologies for the back and forth 😔

**Comment by giuseppebergman** [comment] 2018-03-12 21:40
Here it is, no problem. Thank you for looking into it!
The bug's still there, though there are less lines in the console, so I guess it's a progress :)

![Uploading Capture d’écran 2018-03-12 à 22h37'40.png…]()

**Comment by rodi01** [comment] 2018-03-13 00:31
@giuseppebergman thanks again! 

On the console window, could you run this command "window.data"?
Like this:
![screen shot 2018-03-12 at 5 28 06 pm](https://user-images.githubusercontent.com/52461/37316209-0c02ba8e-261b-11e8-8c63-546fb61e0385.png)

Hopefully you will get something like this:
![screen shot 2018-03-12 at 5 28 13 pm](https://user-images.githubusercontent.com/52461/37316220-1e4ca538-261b-11e8-86b1-41b1556dd69e.png)

**Comment by giuseppebergman** [comment] 2018-03-21 17:16
Hey, 

Sorry for being silent so long, I was way too busy these last days.
I don't see "inspect element" anymore when I click on the blank window. I'll try with v3.7.3. and report here.

**Comment by giuseppebergman** [comment] 2018-03-21 17:19
Okay, so there's no dropdown menu displaying anymore when right-clicking in the blank window, with Sketch 49.1 & plugin 3.7.3…

**Comment by rodi01** [comment] 2018-03-21 18:08
@giuseppebergman yeah, sketch changed to access the inspect element. Here is a thread on how to get that back: http://sketchplugins.com/d/665-sketch-49-webview-cannot-be-inspected-element-by-right-click
Basically, you have to enable the flag in sketch with in the command line like this
`defaults write com.bohemiancoding.sketch3 WebKitDeveloperExtras -bool true`

**Comment by rodi01** [comment] 2018-03-21 18:10
@giuseppebergman you will still need the dev version of the plugin. This one should still work
https://www.dropbox.com/s/x8f9i4xo9kgqxds/Rename-It-find-rename.sketchplugin.zip?dl=0

**Comment by rodi01** [comment] 2018-03-21 18:32
😪 Let me see what else I can do, I will keep trying. Thanks for the info.

**Comment by giuseppebergman** [comment] 2018-03-21 22:00
You're welcome, thanks for trying!

**Comment by giuseppebergman** [comment] 2018-03-28 21:12
Update: the Find&replace works in some files, and doesn't in others, with same versions of Sketch and plugin! 
How can I help you find why (sadly I can't share the mentioned files due to NDA clause)?

Giu_

**Comment by rodi01** [comment] 2018-03-28 21:17
@giuseppebergman That's interesting. Does it work on a brand new file with just a couple of rectangles?

**Comment by JasonLang** [comment] 2018-03-29 15:12
HI! I'm seeing a similar issue for "Rename Selected Artboards".

When I select arboards and then run the plugin, I end up in a state with a blank screen. First, I type "10" then "%" and then "n". The window goes blank when entering "n". See the three screens attached. 

![screen shot 2018-03-29 at 11 09 56 am](https://user-images.githubusercontent.com/1686110/38096896-016cb9b0-3342-11e8-8eda-cae2b4736ef9.png)
![screen shot 2018-03-29 at 11 10 02 am](https://user-images.githubusercontent.com/1686110/38096897-0178921c-3342-11e8-9781-999e452e7e37.png)
![screen shot 2018-03-29 at 11 10 06 am](https://user-images.githubusercontent.com/1686110/38096899-0184ba7e-3342-11e8-8615-4ee9c54f6b76.png)

Thanks!

**Comment by rodi01** [comment] 2018-03-29 16:00
@JasonLang huh! Sorry about that 😟
Does that happen to any file?

**Comment by giuseppebergman** [comment] 2018-03-31 09:38
> @giuseppebergman That's interesting. Does it work on a brand new file with just a couple of rectangles?

Yes, it works fine.

**Comment by rodi01** [comment] 2018-04-13 20:40
Just a heads up that I haven't forgotten about this issue, guys. It's been a very busy month at work and I haven't had time to look at this.
In regards to the bug, any of you using any custom plugin that changes the default layer behavior?

**Comment by nicolocampagna** [comment] 2018-06-21 11:18
Hi @rodi01 ,

i have exactly the same problem :(

![screen shot 2018-06-21 at 13 14 20](https://user-images.githubusercontent.com/40461430/41715867-097456cc-7555-11e8-8166-a542efd0ef5e.png)

I've even installed the version released in your last comment and nothing, doesn't work :( :( :( 

HELP MEEEEeeee!!! 
Thanks :)

**Comment by timparker** [comment] 2018-06-21 15:51
I have the same issue :'( this plugin looks like a godsend if this get's fixed 🙏🏻

**Comment by timparker** [comment] 2018-06-21 16:31
I noticed when you're renaming instances of symbols in other documents, it work's fine - but renaming the actual symbols in the main symbols page loads the empty popup.

**Comment by rodi01** [comment] 2018-06-21 18:11
@timparker @nicolocampagna can you guys try this version: https://www.dropbox.com/s/e902wq1njstwe60/Rename-It-webview.zip?dl=1

FIY: This won't work if your Mac OS version is El Captain or lower.

**Closed** 2019-05-14 20:13 UTC
