### ISSUE TITLE
Plugin not working on Catalina. 

### ISSUE THREAD

**Issue by emeforero** [rodi01/RenameIt#123] opened 2019-06-18 14:55 UTC
Hey I love this plugin used it on my work computer and works great. I installed it on my personal laptop on which I'm running the MacOS Catalina Beta and Sketch 55.1 and the plugin does not work. No modal comes up when clicking any of the options.

**Comment by rodi01** [comment] 2019-06-24 17:11
I don't have Catalina running. I'll see if I can find more info on this, thanks for letting me know.

**Comment by PixelPoetix** [comment] 2019-06-26 22:06
Also a big fan of your plugin - use it almost daily! Having the same issue running 55.2 on Catalina beta. I am well aware not to expect everything to work while running a beta OS, so this is just meant to help you get it sorted out. In case it helps, I'm finding that many other plugins I have installed are also not working. If referencing some working ones might help, a couple that ARE working are Copy Paste Position Size and Sketch's own newer Print Export plugin.

**Comment by rodi01** [comment] 2019-06-26 22:13
Yesterday I tested on Catalina and yes the plugin is broken. The issue isn't related to my plugin but to the plugin frameworks that the sketch folks provides. I filed a bug report with them yesterday (https://github.com/skpm/sketch-module-web-view/issues/109), hopefully it will get fixed soon. 

I was actually able to launch the window for the plugin but I can't interact with it.

**Comment by rodi01** [comment] 2019-06-29 19:37
Here is an update. One of the Sketch engineers said that it's an issue with Sketch, hopefully it will be fixed on their next release.

**Closed** 2019-10-23 19:46 UTC
