### ISSUE TITLE
Feature request - Rename Layer to the name of applied style.

### ISSUE THREAD

**Issue by FransSwift** [rodi01/RenameIt#113] opened 2019-05-09 13:47 UTC
Rename select layer: Keyword -> Style Name.

This would work perfect with the plugin **Styles Generator**:
https://github.com/lucaorio/sketch-styles-generator

You can select any amount of layers (text, shapes, or both) and generate Shared Styles for all of them, at once. The Shared Styles are named like the layers. Take a look at the usage section to know more about how to use it.

This way it's easy to create a overview of created styles and easy to manage them.

**Comment by rodi01** [comment] 2019-05-14 20:15
Duplicate of #82

**Closed** 2019-06-04 22:31 UTC
Labels: enhancement
