### ISSUE TITLE
Modal not showing up

### ISSUE THREAD

**Issue by rock-san** [rodi01/RenameIt#121] opened 2019-05-21 05:59 UTC
Hi! Thanks for making this plugin, I use it almost every day. I've been having this issue over the last few days that when I try to select 'Find and Replace Layers/Artboards Names' from the plugins menu (or I type in the shortcut) no modal comes up. I was wondering if anyone else was having this issue?

I'm using version 4.1.4 of Rename-It and version 54.1 of Sketch

**Comment by rodi01** [comment] 2019-05-21 06:03
@rock-san have you tried restarting sketch?

**Comment by rock-san** [comment] 2019-05-21 06:10
Hi @rodi01, I've restarted Sketch (and Abstract since I've been opening up the Sketch files from Abstract) and still no dice. The other two items in the Rename It menu are still working though.

**Comment by rodi01** [comment] 2019-05-21 06:13
Do you see an empty window or nothing at all?

**Comment by rodi01** [comment] 2019-05-21 06:16
Can you remove the plugin all together, restart sketch and install this version: https://github.com/rodi01/RenameIt/releases/download/v4.2.0-BETA/Rename-It.sketchplugin.zip

**Comment by rock-san** [comment] 2019-05-21 06:32
Nothing comes up when I click on it. I've uninstalled it and installed the version you've linked to and restarted but nothing comes up still. I've installed and older version of Rename It from someone else in my team (version 2.03) and have it working now.

**Comment by rock-san** [comment] 2019-05-21 06:41
I'm happy to replicate this issue again if you want to investigate it further. Hopefully it was just me experiencing it. Thanks again Rodi for helping me troubleshoot it though.

**Comment by rodi01** [comment] 2019-05-21 17:07
Do you know if version 4.0 was working for you? When you have some time, could you give it a try:
https://github.com/rodi01/RenameIt/releases/download/v4.0.0/Rename-It.sketchplugin.zip

**Comment by nandorocker** [comment] 2019-05-21 17:12
+1 here
Started after I updated sketch today.

**Comment by rodi01** [comment] 2019-05-21 17:30
Could one of you try to see if there is any error on the console for the latest release?

- Open the console app and  under reports go to:
~/Library/Logs/com.bohemiancoding.sketch3
Go back to Sketch and run the plugin. See if you get any error.

![](https://user-images.githubusercontent.com/52461/42848674-44f28f4a-89d5-11e8-80bb-77968cd88535.png)

**Comment by rodi01** [comment] 2019-05-21 19:59
@nandorocker @rock-san I think I found the issue... Could you guys try the latest version, 4.1.5?

Make sure you restart sketch

**Comment by krdesign** [comment] 2019-05-22 08:00
This is my issue.

<img width="387" alt="Screenshot 2019-05-22 at 09 59 04" src="https://user-images.githubusercontent.com/1135269/58157313-4d851d80-7c78-11e9-886b-0b3295ca9c76.png">

`TypeError: null is not an object (evaluating 'u.symbolMaster().name')
    at i (/Users/stefanofois/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It.sketchplugin/Contents/Sketch/commandFindReplace.js:1:57273)
    at r (/Users/stefanofois/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It.sketchplugin/Contents/Sketch/commandFindReplace.js:1:57521)
    at /Users/stefanofois/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It.sketchplugin/Contents/Sketch/commandFindReplace.js:1:58131
    at forEach[native code] (/)
    at o (/Users/stefanofois/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It.sketchplugin/Contents/Sketch/commandFindReplace.js:1:58100)
    at default (/Users/stefanofois/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It.sketchplugin/Contents/Sketch/commandFindReplace.js:1:62801)
    at __skpm_run (/Users/stefanofois/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It.sketchplugin/Contents/Sketch/commandFindReplace.js:1:62978)
    at __skpm_run[native code] (/)
`

**Comment by rodi01** [comment] 2019-05-22 15:20
@krdesign does that happen on the 4.1.5 version?

**Comment by krdesign** [comment] 2019-05-22 15:35
@rodi01 Yes, I can confirm.
<img width="515" alt="Screenshot 2019-05-22 at 17 35 03" src="https://user-images.githubusercontent.com/1135269/58187890-f69f3880-7cb7-11e9-98cc-8bd47ddbaac7.png">

**Comment by krdesign** [comment] 2019-05-22 15:55
Maybe i think the problem is of mini modal of plugin if i click over the modal and dont do nothing the plugin window does not close but the "z-index" are over sketch if i minimize sketch, i will try to show with a short video.

[Screen Recording 2019-05-22 at 17.52.12.mov.zip](https://github.com/rodi01/RenameIt/files/3208210/Screen.Recording.2019-05-22.at.17.52.12.mov.zip)

**Comment by rodi01** [comment] 2019-05-22 16:11
@krdesign I see... I just pushed a version that tries to keep the window on top all the time and I added extra check for the error that you were seeing. Could you please give it a shot? 

I think you will need to restart Sketch after updating it

**Comment by krdesign** [comment] 2019-05-22 19:40
@rodi01  Thank you!

**Comment by nandorocker** [comment] 2019-05-23 14:20
Works for me :)

**Comment by rodi01** [comment] 2019-05-23 15:25
Thanks you all for the help. I’m going to close this issue. @rock-san try the latest version, it should be working now.

**Closed by rodi01** 2019-05-23 15:25 UTC
